source 'https://github.com/CocoaPods/Specs.git'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

platform :ios, '11.0'
workspace 'Example'

target 'Embedded' do
    project 'Embedded.xcodeproj'    
    pod 'paymentSDK', :path => '../WDeCom/output'
end

target 'Simple' do
    project 'Simple.xcodeproj'
    pod 'paymentSDK', :path => '../WDeCom/output'
end
